# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-todo
  # namespace: my-namespace
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: crud-todo
  template:
    metadata:
      labels:
        app: crud-todo
    spec:
      containers:
        - name: crud-todo
          image: todo_backend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000 # Adjust the port if needed
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:admin@crud-todo-service/tododb"  # Update with your database connection details
  
