apiVersion: v1
kind: Service
metadata:
  name: crud-todo-service
spec:
  selector:
    app: crud-todo
  ports:
    - protocol: TCP
      port: 3000  # The port your Flask app listens on
      targetPort: 3000  # The port your Flask app container listens on
      nodePort: 30080 # this is the default node port
  type: NodePort
  