version: "3.9"
services:
  database:
    image: todo_psql
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask:
    depends_on:
      - database
    image: todo_backend
    ports:
      - "3000:3000"
    # environment:
    # volumes: 

volumes:
  pgdata: {}